### ISSUE TITLE
Do not reserve 'shift' and 'ctrl' in Apainter

### ISSUE THREAD

**Issue by shostikk** [aamks/aamks#21]
Do not reserve 'shift' and 'ctrl' in Apainter. Using them as key commands prevent's their use for their normal purposes like text selection, print screen, etc.

**Comment by mimooh** [comment]
Apainter is a webapp. See https://editor.method.ac/ -- apps do overwrite ctrl, shift, alt or right-clicks. Perhaps we have conflicts with useful shortcuts like print screen -- I can replace those, since all our shortcuts are arbitrary. But I'd rather don't stay away from at least CTRL, as I see in the devel version of Apainter.

**Comment by shostikk** [comment]
Using CTRL is of course fine for commands.
But SHIFT is needed in text box editing or similar.

Thanks.

**Comment by mimooh** [comment]
Shortcuts have been reworked. CTRL is still used, but not SHIFT.
