### ISSUE TITLE
polygon obstacles

### ISSUE THREAD

**Issue by mimooh** [aamks/aamks#27]
Worker.py fails at processing polygon obstacles. See navmesh demo.

**Comment by akrasuski** [comment]
I'm a little bit confused with the current worker code, for example, I don't know what is this rvo_dto.py line 59: 
   simulation_id = 1 #przykladowa symulacja
   self.evac_data = self.json.read("{}/workers/{}/evac.json".format(os.environ['AAMKS_PROJECT'], simulation_id))
        self.all_evac = self.evac_data["FLOORS_DATA"]["0"]["EVACUEES"]

Hence I don't know whether to commit or not to commit. 

The solution to this issue is worker.py line 196: 
            for obst in self.obstacles['obstacles'][str(floor)]:
                coords = list()
                for coord in obst:
                    tuple_coord = tuple(coord)
                    coords.append(tuple_coord)
                coords.append(tuple(obst[1]))
                obstacles.append(coords)

**Comment by akrasuski** [comment]
Seems fixed:  https://github.com/aamks/aamks/commit/6dee9acd949ff98aeb262d438f7a9fb6056d1074

**Comment by mimooh** [comment]
Yes, it works
