### ISSUE TITLE
Restore default door weights for room

### ISSUE THREAD

**Issue by kowalskiw** [aamks/aamks#293]
Once room exit weights are changed they default behavior cannot be restored in GUI. User is forced to search for "room_exits_weights" in text mode and remove those elements manually from geometry JSON.

**Comment by kowalskiw** [comment]
Same issue was observed for final door weights. Once attached/changed weighing feature cannot be disabled.

**Comment by AleksanderKamienski** [comment]
Do you have a saved scenario where this error occurred? I tried to recreate it locally but it works for me locally

**Comment by AleksanderKamienski** [comment]
Generally, the logic works in such a way that by default there is no "exit_weight" field and only when we change this value does it appear in the cad.json file. When we change exit_weight to 10 again, this value is updated to 10. By default, when we create doors, all weights are set to 10, but this is not visible in the cad.json file. The program works and I don't know if it makes sense to change it because I could change it so that "exit_weight":"10" is entered by default everywhere in the cad.json file or make it so that when "exit_weight" is set to "10" this field disappears from cad. json. Then it would be more consistent, but the program will work the same as now.

**Comment by AleksanderKamienski** [comment]
In my case, after resetting the door weight to 10, agents normally exit through this door. I contacted Michał and asked him to explain what exactly they meant with this error

**Comment by kowalskiw** [comment]
Thanks, me serving as a proxy is not the best idea ;-) 

If you will not be able to reproduce the error with the v2.0.1, please close the issue as not planned, eventually.

**Comment by kowalskiw** [comment]
Not able to reproduce
