### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by mmackiewicz97** [aamks/aamks#58]
worker.py :284 time.sleep(1) probably couses freezing simulations

**Comment by kowalskiw** [comment]
It seems like the loop was a workaround for broken CFAST results. Resolved in pull reguest #64 - sleeping was replaced with exception for unfinished CFAST simulations. Since then when fire model finishes with error or freezes evac simulation is skipped.

While testing everything was fine, nevertheless we should be attentive for any bugs in this area.
