### ISSUE TITLE
problem with envvariables in worker.py

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#61]
![image](https://user-images.githubusercontent.com/33099769/221139837-93fae28b-dfbf-486e-a354-865741b4a3c5.png)

There is a problem with environment variables AAMKS_WORKER, AAMKS_PATH, AAMKS_SERVER in worker.py. 

The program has a problem with downloading environment variables from ~/.bashrc as user aamks (gearman processes on workers are started by aamks user) . Therefore, the values ​​at the moment are entered in the program code.

**Comment by mimooh** [comment]
Possible locations of AAMKS env:
~/.bashrc
/etc/apache2/envvars
/etc/aamksconf.json

https://github.com/aamks/aamks/blob/master/installer/worker_install.sh:
echo "{ \"AAMKS_SERVER\": \"$_AAMKS_SERVER\" }"  | sudo tee
/etc/aamksconf.json

Karol Kreński

**Comment by kowalskiw** [comment]
The reason of the bug was `nohup` sealed environment.

Since https://github.com/aamks/aamks/commit/38c0003f28b09824daffeeb453505179626982da  those envvars 
are passed to worker along with aRun function and it works just fine.

_Source: https://unix.stackexchange.com/questions/308370/how-can-i-set-environment-variables-for-a-program-executed-using-nohup_

@Gdzieniegdzie, @mmackiewicz97 - maybe it helps a little with #57 ?
